server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hnnw/tensquare_cofig.git
  rabbitmq:
    host: 192.168.132.133
management:
  endpoints:
    web:
      exposure:
        include: bus‐refresh