server:
  port: 9012
spring:
  application:
    name: tensquare-web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-user: user/**
jwt:
  config:
    key: tensquare
  filter:
    allowPaths:
      - /user/user/login
      - /user/admin/login


